name: Publish Package

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          scope: '@itsliaaa'

      - run: corepack enable
      - run: yarn install --frozen-lockfile

      - name: Publish to npm
        run: npm publish --access public --provenance --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup GitHub Packages
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
          scope: '@itsliaaa'

      - name: Publish to GitHub Packages
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}